#!/usr/bin/python
# -*- coding: UTF-8 -*-
import os, sys

import sqlite3
from sqlite3 import Error


def sql_connection():
    try:
        con = sqlite3.connect('Dance.db')
        return con
    except Error:
        print(Error)


def sql_input(con, table, data):
    try:
        cursorObj = con.cursor()
        ID_current = cursorObj.execute('Select max(id) from ' + table).fetchone()[0]
        print(ID_current)
        if ID_current == None:
            ID_current = 0
        else:
            ID_current += 1
        cursorObj.execute('Insert into ' + table + ' values(' + str(ID_current) + ',' + data + ')')
        con.commit()
        print('success Insert ')
    except Error as err:
        print(err)


def sql_input_non_id(con, table, data):
    try:
        cursorObj = con.cursor()
        cursorObj.execute('Insert into ' + table + ' values(' + data + ')')
        con.commit()
        print('success Insert ')
    except Error as err:
        print(err)

con = sql_connection()
con.commit()


sql_input(con, 'User', "'admin', 'admin', 'Администратор', 'admin@mail.ru', '+79008001010', 'Россия', 45, 'Admin', 1")
sql_input(con, 'User', "'alina', 'alina', 'Дикарева Алина', 'alina@mail.ru', '+79008001011', 'Россия', 20, 'Учусь на программиста и фантастически танцую.', 0")
sql_input(con, 'User', "'tomjohns', 'tommy', 'Том Джонс', 'tommy@mail.ru', '+79008001012', 'Англия', 43, 'Член жюри и первокласный танцор.', 0")
sql_input(con, 'User', "'vasiva', 'vasjaiv', 'Василий Иванов', 'vasja@mail.ru', '+79008001013', 'Россия', 19, 'Танцор, учусь в МГУ.', 0")
sql_input(con, 'User', "'redigor', 'reddy', 'Игорь Краснов', 'redigor@mail.ru', '+79008001014', 'Россия', 20, 'Люблю танцевать, танцую с детства.', 0")
sql_input(con, 'User', "'antiv', 'reddy', 'Антон Иванов', 'anton@mail.ru', '+79008001015', 'Россия', 21, 'Обожаю танцевать брейк-данс.', 0")
sql_input(con, 'User', "'valery', 'reddy', 'Валерий Власенко', 'valery@mail.ru', '+79008001016', 'Россия', 18, 'Танцы-это смысл моей жизни.', 0")
sql_input(con, 'User', "'mixaoks', 'reddy', 'Оксана Михайлова', 'mixaoks@mail.ru', '+79008001017', 'Россия', 18, 'В детстве мама привела меня на бальные танцы и я нашла в этом смысл существования.', 0")
sql_input(con, 'User', "'kitjex', 'reddy', 'Кит Джексон', 'kitjex@mail.ru', '+79008001018', 'США', 29, 'Судья, чемпион мира в стиле Модерн 2010.', 0")
sql_input(con, 'User', "'nikmor', 'reddy', 'Николай Мороз', 'nikmor@mail.ru', '+79008001019', 'Россия', 20, 'Брейк-данс подарил мне желание развиваться.', 0")
sql_input(con, 'User', "'chimku', 'reddy', 'Чим Ку', 'kuku@mail.ru', '+79008001020', 'Китай', 20, 'Танцую бальные танцы.', 0")
sql_input(con, 'User', "'amilin', 'reddy', 'Ами Лин', 'amilin@mail.ru', '+79008001021', 'Япония', 20, 'Танец - это целая история.', 0")
sql_input(con, 'User', "'kadzu', 'reddy', 'Кадзу Рэй', 'kadzu@mail.ru', '+79008001022', 'Япония', 20, 'Танцор и исполнитель авторской музыки.', 0")
sql_input(con, 'User', "'takeshi', 'reddy', 'Такеши Син', 'takeshi@mail.ru', '+79008001023', 'Южная Корея', 26, 'Танцую, учусь и работаю в библиотеке.', 0")
sql_input(con, 'User', "'stuart', 'reddy', 'Джеймс Стюарт', 'stuartgames@mail.ru', '+79008001024', 'Англия', 21, 'Моя жизнь - танец.', 0")
sql_input(con, 'User', "'doremma', 'reddy', 'Эмма Дор', 'doremma@mail.ru', '+79008001025', 'Англия', 22, 'Вместе с моим партнёром мы прошли многое. Участвовали во многих соревнованиях.', 0")
sql_input(con, 'User', "'vivienbond', 'reddy', 'Вивьен Бонд', 'vivienbond@mail.ru', '+79008001026', 'Франция', 24, 'Стараюсь во всём быть лучшей.', 0")
sql_input(con, 'User', "'ivansorokin', 'reddy', 'Иван Сорокин', 'ivansorokin@mail.ru', '+79008001027', 'Россия', 21, 'Посещаю балы и иногда танцую в кино.', 0")
sql_input(con, 'User', "'olgache', 'reddy', 'Ольга Чернова', 'olgache@mail.ru', '+79008001028', 'Россия', 19, 'В будущем хочу стать тренером и воспитывать новое поколение выдающихся танцоров.', 0")
sql_input(con, 'User', "'schwein', 'reddy', 'Марк Швайн', 'schwein@mail.ru', '+79008001029', 'Германия', 21, 'Танец - это битва. Танец - это огонь.', 0")
sql_input(con, 'User', "'strauss', 'reddy', 'Инга Штраус', 'strauss@mail.ru', '+79008001030', 'Германия', 22, 'Танцую с 4х лет, стараюсь во всём быть лучшей.', 0")
sql_input(con, 'User', "'pablodolce', 'reddy', 'Пабло Дольче', 'pablodolce@mail.ru', '+79008001031', 'Италия', 21, 'Танец помогает раскрыться и обрести уверенность в себе и своих силах.', 0")
sql_input(con, 'User', "'frenapoli', 'reddy', 'Фредерика Наполи', 'frenapoli@mail.ru', '+79008001032', 'Италия', 23, 'Оценки - это не главное. Главное - получить массу положительных эмоций. ', 0")
sql_input(con, 'User', "'limun', 'reddy', 'Ли Мун', 'limun@mail.ru', '+79008001033', 'Китай', 25, 'Хип-хоп - это чудесно. С детства увлекаюсь этой культурой.', 0")
sql_input(con, 'User', "'lunich', 'reddy', 'Лунь Чао', 'lunich@mail.ru', '+79008001034', 'Китай', 21, 'Модерн-это супер направление.', 0")
sql_input(con, 'User', "'billberta', 'reddy', 'Берта Билл', 'billberta@mail.ru', '+79008001035', 'Норвегия', 22, 'Обожаю танцевать.', 0")
sql_input(con, 'User', "'roiuil', 'reddy', 'Рой Уильямс', 'roiuil@mail.ru', '+79008001036', 'США', 24, 'Брейк-данс позволяет держать себя в форме.', 0")
sql_input(con, 'User', "'schell', 'reddy', 'Тобиас Шелл', 'schell@mail.ru', '+79008001038', 'Нидерланды', 21, 'Мои родители были профессиональными танцорами и я пошёл по их стопам.', 0")
sql_input(con, 'User', "'franz', 'reddy', 'Франц Шульц', 'franz@mail.ru', '+79008001039', 'Германия', 22, 'Я не мечтаю о победе. Я её одержу.', 0")
sql_input(con, 'User', "'karlbenz', 'reddy', 'Карл Бенц', 'karlbenz@mail.ru', '+79008001040', 'Германия', 22, 'Готов бороться до последнего. Занимаюсь танцами всю свою жизнь.', 0")
sql_input(con, 'User', "'likach', 'reddy', 'Лика Чезаре', 'licach@mail.ru', '+79008001041', 'Италия', 21, 'Танцы дарят красивую осанку и хорошее настроение.', 0")
sql_input(con, 'User', "'white', 'reddy', 'Майкл Уайт', 'white@mail.ru', '+79008001042', 'Англия', 45, 'Член жюри, финалист чемпионата мира по бальным танцам 2005', 0")
sql_input(con, 'User', "'alank', 'reddy', 'Алан Капри', 'alank@mail.ru', '+79008001043', 'Италия', 20, 'Живу, путешествую, танцую.', 0")
sql_input(con, 'User', "'tomlk', 'reddy', 'Том Лок', 'tomlk@mail.ru', '+79008001044, 'Англия', 21, 'В танцах обретаю себя.', 0")
sql_input(con, 'User', "'dgimmy', 'reddy', 'Джим Солт', 'dgimmy@mail.ru', '+79008001045', 'США', 22, 'Танцую лучше всех.', 0")
sql_input(con, 'User', "'betty', 'reddy', 'Бетти Найт', 'betty@mail.ru', '+79008001046', 'США', 21, 'Бальные танцы дарят нам атмосферу ушедших веков.', 0")
sql_input(con, 'User', "'lanaf', 'reddy', 'Лана Фарис', 'lanaf@mail.ru', '+79008001047', 'США', 20, 'Люблю танцевать и путешествовать.', 0")
sql_input(con, 'User', "'valery', 'reddy', 'Валерия Демченко', 'valery@mail.ru', '+79008001048, 'Россия', 30, 'Член жюри.', 0")
sql_input(con, 'User', "'kortny', 'reddy', 'Кортни Лав', 'kortny@mail.ru', '+79008001049', 'США', 20, 'Я настроена на победу.', 0")
sql_input(con, 'User', "'timoti', 'reddy', 'Тимоти Буш', 'timoti@mail.ru', '+79008001050', 'США', 20, 'Танцы - это круто.', 0")
sql_input(con, 'User', "'armenz', 'zz45zzz', 'Армен Забаргян', 'armen@mail.ru', '+79008001051', 'Армения', 22, 'Танцы позволяют раскрыть себя и свой талант в полной мере.', 0")
sql_input(con, 'User', "'anailka', 'anail', 'Анаиль Канакян', 'anail@mail.ru', '+79008001052', 'Армения', 21, 'Я танцую с детсва вместе с моим партнёром. Нам хочется внести в бальные танцы наш национальный колорит.', 0")
print(con.cursor().execute('select * from User').fetchall())


sql_input(con, 'Team', "'Дикарева Алина', 'Главная претендентка на победу.'")
sql_input(con, 'Team', "'Двое в Саратове', 'Одержали победу в 2020 на чемпионате России по брейк-дансу.'")
sql_input(con, 'Team', "'Антон Иванов', 'С детства привык быть первым.'")
sql_input(con, 'Team', "'Валерий и Оксана', 'Являются дествующими чемпионами Европы 2020.'")
sql_input(con, 'Team', "'НикМор', 'Считается одним из самых одарённых участников проекта за всю историю проведения чемпионата.'")
sql_input(con, 'Team', "'Чим и Ами', 'Вносят восточный колорит во все танцы программы.'")
sql_input(con, 'Team', "'Кадзу', 'Его грация и лёгкость покоряет сердца.'")
sql_input(con, 'Team', "'Такеши', 'Неповторимый стиль и акробатические движения делают его непревзойдённым мастером в своём направлении.'")
sql_input(con, 'Team', "'Джеймс и Элина', 'Одни из претендентов на победу. Лучше всех танцуют вальс.'")
sql_input(con, 'Team', "'Вивьен', 'Поразительно гибкая и смелая танцовщица, покоряет сердца зрителей с первых секунд выступления.'")
sql_input(con, 'Team', "'Иван и Ольга', 'Чемпионы России 2018.'")
sql_input(con, 'Team', "'Марк и Инга', 'Их выступление поражает зрителя ритмичностью и артистизмом.'")
sql_input(con, 'Team', "'Пабло и Фредерика', 'Танцуют в лучших традициях Италии.'")
sql_input(con, 'Team', "'Ли', 'Стиль и энергетика этой танцовщицы покоряют.'")
sql_input(con, 'Team', "'Лунь', 'Мастерство этого юного танцора поражает.'")
sql_input(con, 'Team', "'Берта', 'Берта заставляет поновому взглянуть на привычные танцевальные стили.'")
sql_input(con, 'Team', "'Рой', 'Заряжает своей энергией даже самого скромного зрителя.'")
sql_input(con, 'Team', "'Тобиас', 'Является чемпионом Европы 2018.'")
sql_input(con, 'Team', "'Франц', 'Танцор, который приковывывает к себе взгляд с первой минуты.'")
sql_input(con, 'Team', "'Карл', 'Зрители с нетерпением ждут его выход на танцпол.'")
sql_input(con, 'Team', "'Лика', 'Прекрасно танцует. Является одной из претендентов на победу.'")
sql_input(con, 'Team', "'Алан', 'Чемпион Италии в стиле модерн в 2017м году. '")
sql_input(con, 'Team', "'Том', 'Своим танцем выражает гамонию человека и окружающего мира.'")
sql_input(con, 'Team', "'Джим и Бетти', 'Энергичны, молоды и красивы. Побеждают в соревнованиях по бальным танцам с детства.'")
sql_input(con, 'Team', "'Лана', 'В своих танцах сочетает культуры разных народов.'")
sql_input(con, 'Team', "'Кортни и Тимоти', 'Образец элегантности и стиля. Безупречно танцуют.'")
sql_input(con, 'Team', "'Армен и Анаиль', 'Сочетают танец с национальными обычиями и традициями.'")



print(con.cursor().execute('select * from Team').fetchall())


sql_input(con, 'Style', "'Контемпорари', 'Контемпорари (англ. contemporary dance) — современный сценический танец, включающий в себя самые различные направления и техники. Contemporary dance сформировался на основе танца модерн. Термин «contemporary dance» появился в Европе в 1970-е годы.'")
sql_input(con, 'Style', "'Брейк-данс', 'Брейк-данс (англ. breakdance) — уличный танец, сформировавшийся в Нью-Йорке в 60-х годах XX века. Это зрелищное направление, сочетающее в себе сложные акробатические движения и демонстрирующее превосходную физическую форму танцора.'")
sql_input(con, 'Style', "'Спортивные бальные танцы', 'Спортивно-бальные танцы — группа различных парных танцев, некоторые из которых имеют народные истоки. Исполнялись на балах, которые проводились в помещениях, застеленных паркетом. Из огромного разнообразия как элитных (историко-бытовых), так и народных танцев в группу бальных попали танцы, характеризующиеся 2 признаками: все бальные танцы являются парными; пару составляют мужчина и женщина, но есть исключения, так как в Англии уже принято танцевать в однополых составах. В настоящее время к бальным танцам относят 10 различных танцев, разбитых на две программы. Во всём танцевальном мире соревнования по спортивным танцам делятся на 2 программы: европейскую (Standard, Modern или Ballroom), латиноамериканскую (Latin) или их иногда называют десяткой танцев. В европейскую программу входят: медленный вальс (Бостон), квикстеп (быстрый фокстрот), венский вальс, танго, медленный фокстрот. В латиноамериканскую: самба, ча-ча-ча, румба, пасодобль, джайв.'")
sql_input(con, 'Style', "'Модерн', 'Танец модерн — одно из направлений современной зарубежной хореографии, зародившееся в кон. XIX — нач. XX веков в США и Германии. Термин «Танец модерн» появился в США для обозначения сценической хореографии, отвергающей традиционные балетные формы.'")



print(con.cursor().execute('select * from Style').fetchall())

sql_input(con, 'Championship', "2019, 'В субботу, 21 декабря, в новом концертом зале «Екатеринбург-Экспо» прошел чемпионат мира по 10 танцам среди профессионалов Всемирного танцевального совета (WDC). На паркет вышли танцоры из Великобритании, китайского Тайбэя, Новой Зеландии, США, Финляндии, ЮАР, Японии и, конечно, России. В программе 10 танцев исполнители показывают европейские и латиноамериканские танцы, что требует от танцоров двойного объема энтузиазма, энергии и сил. Не всем такое под силу, поэтому численность танцоров в «десятке» не так велика, как в отдельных программах.'")
sql_input(con, 'Championship', "2020, ' Всемирная Федерация Танцевального Спорта провела 22 ноября в Китае Чемпионат Мира по шоу в европейской и латиноамериканской программах бального танца. DanceSportGlobal.com предлагает итоги этих соревнований. За день до этого турнира здесь же, в городе Чэнду, состоялся Чемпионат Мира по 10 танцам'")
sql_input(con, 'Championship', "2021, 'Грядущий чемпионат мира обещает быть самым зрелищным и массовым за всю историю проведения турнира. '")


sql_input_non_id(con, 'Jury_Stage', " 2, 2, 1")
sql_input_non_id(con, 'Jury_Stage', " 2, 2, 0")
sql_input_non_id(con, 'Jury_Stage', " 2, 2, 2")
sql_input_non_id(con, 'Jury_Stage', " 8, 1, 0")
sql_input_non_id(con, 'Jury_Stage', " 8, 1, 1")
sql_input_non_id(con, 'Jury_Stage', " 8, 1, 2")
sql_input_non_id(con, 'Jury_Stage', " 31, 2, 3")
sql_input_non_id(con, 'Jury_Stage', " 31, 0, 2")
sql_input_non_id(con, 'Jury_Stage', " 31, 2, 1")
sql_input_non_id(con, 'Jury_Stage', " 37, 2, 1")
sql_input_non_id(con, 'Jury_Stage', " 37, 2, 3")
sql_input_non_id(con, 'Jury_Stage', " 37, 2, 0")
sql_input_non_id(con, 'Jury_Stage', " 2, 0, 1")
sql_input_non_id(con, 'Jury_Stage', " 2, 0, 0")
sql_input_non_id(con, 'Jury_Stage', " 8, 2, 3")
sql_input_non_id(con, 'Jury_Stage', " 8, 0, 3")
sql_input_non_id(con, 'Jury_Stage', " 8, 1, 3")

sql_input_non_id(con, 'Style_Team_Champ', " 0, 0, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 1, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 2, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 3, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 4, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 5, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 6, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 7, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 8, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 9, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 10, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 11, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 12, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 13, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 14, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 15, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 16, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 17, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 18, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 19, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 20, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 21, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 22, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 23, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 24, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 25, 2")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 26, 2")

sql_input_non_id(con, 'Style_Team_Champ', " 0, 0, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 1, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 2, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 3, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 4, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 5, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 6, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 7, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 8, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 9, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 10, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 11, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 12, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 13, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 14, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 15, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 16, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 17, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 18, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 19, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 20, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 21, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 22, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 23, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 24, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 25, 1")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 26, 1")

sql_input_non_id(con, 'Style_Team_Champ', " 0, 0, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 1, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 2, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 3, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 4, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 5, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 6, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 7, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 8, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 9, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 10, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 11, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 12, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 13, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 14, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 15, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 16, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 17, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 18, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 1, 19, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 20, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 21, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 0, 22, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 23, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 3, 24, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 25, 0")
sql_input_non_id(con, 'Style_Team_Champ', " 2, 26, 0")

sql_input_non_id(con, 'User_Team', " 1, 0")
sql_input_non_id(con, 'User_Team', " 3, 1")
sql_input_non_id(con, 'User_Team', " 4, 1")
sql_input_non_id(con, 'User_Team', " 5, 2")
sql_input_non_id(con, 'User_Team', " 6, 3")
sql_input_non_id(con, 'User_Team', " 7, 3")
sql_input_non_id(con, 'User_Team', " 9, 4")
sql_input_non_id(con, 'User_Team', " 10, 5")
sql_input_non_id(con, 'User_Team', " 11, 5")
sql_input_non_id(con, 'User_Team', " 12, 6")
sql_input_non_id(con, 'User_Team', " 13, 7")
sql_input_non_id(con, 'User_Team', " 14, 8")
sql_input_non_id(con, 'User_Team', " 15, 8")
sql_input_non_id(con, 'User_Team', " 16, 9")
sql_input_non_id(con, 'User_Team', " 17, 10")
sql_input_non_id(con, 'User_Team', " 18, 10")
sql_input_non_id(con, 'User_Team', " 19, 11")
sql_input_non_id(con, 'User_Team', " 20, 11")
sql_input_non_id(con, 'User_Team', " 21, 12")
sql_input_non_id(con, 'User_Team', " 22, 12")
sql_input_non_id(con, 'User_Team', " 23, 13")
sql_input_non_id(con, 'User_Team', " 24, 14")
sql_input_non_id(con, 'User_Team', " 25, 15")
sql_input_non_id(con, 'User_Team', " 26, 16")
sql_input_non_id(con, 'User_Team', " 27, 17")
sql_input_non_id(con, 'User_Team', " 28, 18")
sql_input_non_id(con, 'User_Team', " 29, 19")
sql_input_non_id(con, 'User_Team', " 30, 20")
sql_input_non_id(con, 'User_Team', " 32, 21")
sql_input_non_id(con, 'User_Team', " 33, 22")
sql_input_non_id(con, 'User_Team', " 34, 23")
sql_input_non_id(con, 'User_Team', " 35, 23")
sql_input_non_id(con, 'User_Team', " 36, 24")
sql_input_non_id(con, 'User_Team', " 38, 25")
sql_input_non_id(con, 'User_Team', " 39, 25")
sql_input_non_id(con, 'User_Team', " 40, 26")
sql_input_non_id(con, 'User_Team', " 41, 26")



sql_input_non_id(con, 'Ratings', " 1, 8, 0, 0, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 1, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 2, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 3, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 4, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 5, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 6, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 7, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 8, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 9, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 10, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 11, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 12, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 13, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 14, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 15, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 16, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 17, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 18, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 19, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 20, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 21, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 22, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 23, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 24, 5, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 25, 4, 0")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 26, 5, 0")

sql_input_non_id(con, 'Ratings', " 1, 8, 0, 0, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 1, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 2, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 3, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 4, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 5, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 6, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 7, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 8, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 9, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 10, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 11, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 12, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 13, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 14, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 15, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 16, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 17, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 18, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 19, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 20, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 21, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 22, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 23, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 24, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 25, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 26, 4, 1")

sql_input_non_id(con, 'Ratings', " 1, 8, 0, 0, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 1, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 2, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 3, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 4, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 5, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 6, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 7, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 2, 2, 8, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 9, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 10, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 11, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 12, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 13, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 14, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 15, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 16, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 17, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 18, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 1, 19, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 20, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 21, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 0, 22, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 23, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 3, 24, 5, 1")
sql_input_non_id(con, 'Ratings', " 1, 8, 2, 25, 4, 1")
sql_input_non_id(con, 'Ratings', " 1, 2, 2, 26, 5, 1")

sql_input_non_id(con, 'Ratings', " 0, 2, 0, 0, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 1, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 2, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 3, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 4, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 5, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 6, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 7, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 8, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 9, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 10, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 11, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 12, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 13, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 14, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 15, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 16, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 17, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 18, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 19, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 20, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 21, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 22, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 23, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 24, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 25, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 26, 4, 1")

sql_input_non_id(con, 'Ratings', " 0, 2, 0, 0, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 1, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 2, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 3, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 4, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 5, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 6, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 7, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 8, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 9, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 10, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 11, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 12, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 13, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 14, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 15, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 16, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 17, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 18, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 19, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 20, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 21, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 2, 0, 22, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 23, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 24, 5, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 25, 4, 1")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 26, 5, 1")

sql_input_non_id(con, 'Ratings', " 0, 37, 0, 0, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 1, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 2, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 3, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 4, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 5, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 6, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 7, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 8, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 37, 0, 9, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 10, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 11, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 12, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 13, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 14, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 37, 0, 15, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 16, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 17, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 37, 0, 18, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 2, 1, 19, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 37, 0, 20, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 21, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 37, 0, 22, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 23, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 8, 3, 24, 5, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 25, 4, 0")
sql_input_non_id(con, 'Ratings', " 0, 31, 2, 26, 5, 0")

sql_input_non_id(con, 'Ratings', " 2, 2, 0, 0, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 1, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 2, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 3, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 4, 4, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 5, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 6, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 3, 7, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 8, 4, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 9, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 10, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 11, 4, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 12, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 13, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 14, 4, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 15, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 16, 4, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 3, 17, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 18, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 19, 4, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 20, 4, 1")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 21, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 22, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 23, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 3, 24, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 25, 4, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 26, 5, 1")

sql_input_non_id(con, 'Ratings', " 2, 37, 0, 0, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 1, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 2, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 3, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 4, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 5, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 3, 6, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 7, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 8, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 9, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 10, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 11, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 12, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 13, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 3, 14, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 15, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 16, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 17, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 18, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 19, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 20, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 3, 21, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 22, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 23, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 24, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 25, 5, 1")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 26, 5, 1")

sql_input_non_id(con, 'Ratings', " 2, 37, 0, 0, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 1, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 2, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 3, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 4, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 5, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 6, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 37, 3, 7, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 8, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 9, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 10, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 11, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 12, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 13, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 14, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 15, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 16, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 37, 3, 17, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 18, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 1, 19, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 20, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 31, 3, 21, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 37, 0, 22, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 23, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 8, 3, 24, 4, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 25, 5, 0")
sql_input_non_id(con, 'Ratings', " 2, 2, 2, 26, 4, 0")
